apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vuy808b1g-nodejs 
  janus-idp.io/tekton: vuy808b1g-nodejs
  backstage.io/kubernetes-id: vuy808b1g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vuy808b1g-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml